name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Uninstall old Docker version
        run: sudo apt-get remove docker docker-engine docker.io containerd runc
      - name: Enable experimental Docker features
        run: echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
      - name: Install latest Docker version
        run: |
          sudo apt-get update
          sudo apt-get install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
      - name: Show Docker info
        run: docker info
      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{secrets.docker_username}}
          DOCKER_PASSWORD: ${{secrets.docker_password}}
      - name: Make Gradle Wrapper executable
        run: sudo chmod +x ./gradlew
      - name: Run Gradle Wrapper
        run: ./gradlew dockerBuildPush
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
